export const brasilStates = [
	{ id: 1, Uf: "AC", State: "Acre" },
	{ id: 2, Uf: "AL", State: "Alagoas" },
	{ id: 3, Uf: "AP", State: "Amapá" },
	{ id: 4, Uf: "AM", State: "Amazonas" },
	{ id: 5, Uf: "BA", State: "Bahia" },
	{ id: 6, Uf: "CE", State: "Ceará" },
	{ id: 7, Uf: "DF", State: "Distrito Federal" },
	{ id: 8, Uf: "ES", State: "Espírito Santo" },
	{ id: 9, Uf: "GO", State: "Goías" },
	{ id: 10, Uf: "MA", State: "Maranhão" },
	{ id: 11, Uf: "MT", State: "Mato Grosso" },
	{ id: 12, Uf: "MS", State: "Mato Grosso do Sul" },
	{ id: 13, Uf: "MG", State: "Minas Gerais" },
	{ id: 14, Uf: "PA", State: "Pará" },
	{ id: 15, Uf: "PB", State: "Paraíba" },
	{ id: 16, Uf: "PR", State: "Paraná" },
	{ id: 17, Uf: "PE", State: "Pernambuco" },
	{ id: 18, Uf: "PI", State: "Piauí" },
	{ id: 19, Uf: "RJ", State: "Rio de Janeiro" },
	{ id: 20, Uf: "RN", State: "Rio Grande do Norte" },
	{ id: 21, Uf: "RS", State: "Rio Grande do Sul" },
	{ id: 22, Uf: "RO", State: "Rondônia" },
	{ id: 23, Uf: "RR", State: "Roraíma" },
	{ id: 24, Uf: "SC", State: "Santa Catarina" },
	{ id: 25, Uf: "SP", State: "São Paulo" },
	{ id: 26, Uf: "SE", State: "Sergipe" },
	{ id: 27, Uf: "TO", State: "Tocantins" },
];
